import Letters from '@/components/Letters'
import Landing from '@/containers/Landing'
import images from '@/contstants/images'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>REEN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={images.logo.src} />
      </Head>
      <Landing />
    </>
  )
}
